services:
  - type: web
    name: smart-parking-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    plan: free
