groups:
- name: smart-parking-alerts
  rules:
  # High CPU usage
  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage detected"
      description: "CPU usage is above 80% for more than 5 minutes on {{ $labels.instance }}"

  # High Memory usage
  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage detected"
      description: "Memory usage is above 85% for more than 5 minutes on {{ $labels.instance }}"

  # Backend service down
  - alert: BackendServiceDown
    expr: up{job="smart-parking-backend"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Backend service is down"
      description: "Smart Parking Backend API is not responding for more than 1 minute"

  # Frontend service down
  - alert: FrontendServiceDown
    expr: up{job="smart-parking-frontend"} == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Frontend service is down"
      description: "Smart Parking Frontend is not responding for more than 1 minute"

  # Database connection issues
  - alert: DatabaseConnectionError
    expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "High rate of 5xx errors"
      description: "High rate of 5xx errors detected, possible database connection issues"

  # High response time
  - alert: HighResponseTime
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High response time"
      description: "95th percentile response time is above 1 second for more than 5 minutes"

  # Disk space low
  - alert: DiskSpaceLow
    expr: node_filesystem_avail_bytes{fstype!="tmpfs"} / node_filesystem_size_bytes{fstype!="tmpfs"} * 100 < 10
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Disk space is running low"
      description: "Disk space is below 10% on {{ $labels.device }} at {{ $labels.instance }}"

  # Redis down
  - alert: RedisDown
    expr: up{job="redis"} == 0
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Redis is down"
      description: "Redis service is not responding"

  # High number of failed reservations
  - alert: HighFailedReservations
    expr: rate(reservation_failures_total[5m]) > 0.1
    for: 3m
    labels:
      severity: warning
    annotations:
      summary: "High rate of failed reservations"
      description: "High rate of reservation failures detected"